spring:
    application:
        name: exchangerate
    r2dbc:
        # url: r2dbc:postgresql://localhost:5432/mydbreact
        url: r2dbc:postgresql://db:5432/mydbreact
        username: postgres
        password: jhair
    sql:
        init:
            mode: always

external:
    api:
        # url: http://localhost:8080/fixer/latest
        url: http://host.docker.internal:8080/fixer/latest

server:
  port: 7070